In [4]:
a = 10
import tensorflow as tf

In [5]:
import numpy as np


In [6]:
b=90


این چیزایی که ای پایینو هست از سایت 

http://cs231n.github.io/python-numpy-tutorial/#python

آورده شده

In [7]:
print(b)

90


In [8]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,8,10,1,2,1]))

[1, 1, 2, 3, 6, 8, 10]


In [9]:
3//4


0

In [10]:
8//4

2

In [11]:
9//4

2

In [12]:
arr=[3,6,8,10,1,2,1]

In [13]:
pivot = arr[len(arr) // 2]

In [14]:
arr

[3, 6, 8, 10, 1, 2, 1]

In [15]:
pivot

10

In [16]:
pivot

10

In [17]:
    left = [x for x in arr if x < pivot]

In [20]:
left

[3, 6, 8, 1, 2, 1]

In [21]:
middle

[10]

In [22]:
right

[]

In [24]:
a= [1 , 2 ] + [3 , 4]

In [25]:
a

[1, 2, 3, 4]

# نوع داده های اصلی 

In [26]:
x=3

In [27]:
x+1

4

In [28]:
print(type(x))

<class 'int'>


In [29]:
print(x+1
     )

4


In [30]:
x**2

9

In [31]:
x+=1

In [33]:
y=2.5

In [35]:
print(type(y))

<class 'float'>


خیلی حال کردم

In [36]:
print(y, y + 1, y * 2, y ** 2)

2.5 3.5 5.0 6.25


In [38]:
ش=complex(3, 2)

In [39]:
ش

(3+2j)

In [40]:
ش.conjugate

<function complex.conjugate>

In [41]:
c.conjugate(ش)

NameError: name 'c' is not defined

In [42]:
ش.conjugate()

(3-2j)

In [43]:
abs(ش)

3.605551275463989

In [44]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

<class 'bool'>
False
True
False
True


In [46]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world 

hello
5


In [48]:
hw = hello + ' ' + world 

In [49]:
type(hello)

str

In [59]:
s = "hellooooooooo00000000000"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(70))

Hellooooooooo00000000000
HELLOOOOOOOOO00000000000
                                              hellooooooooo00000000000


In [60]:
print(s.center(7))  

hellooooooooo00000000000


In [61]:
print(s.center(70))  

                       hellooooooooo00000000000                       


In [62]:
print(s.center(7))  

hellooooooooo00000000000


In [63]:
xs = [3, 1, 2] 

In [64]:
xs[2]

2

In [65]:
type(xs)

list

In [66]:
type(arr)

list

In [67]:
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)  

[3, 1, 2] 2
2
[3, 1, 'foo']


In [68]:
type(xs)

list

In [69]:
type(xs[2])


str

خود لیست یک نوع است و المانهای آن هم میتوانند نوعهای مختلفی داشته باشند

In [70]:
xs.pop(1)

1

In [71]:
xs

[3, 'foo']

In [72]:
xs.pop(1)

'foo'

In [73]:
xs

[3]

In [83]:
x=[1 , 2 , 3, 4, 5, 6, 7 , 8]

In [84]:
x.pop(2)

3

In [85]:
x

[1, 2, 4, 5, 6, 7, 8]

In [86]:
x[0]

1

In [88]:
nums = list(range(5))

In [89]:
nums

[0, 1, 2, 3, 4]

In [90]:
print(nums[2:4])

[2, 3]


In [91]:
nums[:-1]

[0, 1, 2, 3]

In [92]:
nums

[0, 1, 2, 3, 4]

In [93]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [95]:
animals = ['cat', 'dog', 'monkey']
for i in animals:
    print(i)

cat
dog
monkey


In [96]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


In [98]:
enumerate(arr)

In [99]:
'#%d: %s' % (idx + 1, animal)

'#3: monkey'

In [106]:
arr= [1, 2, 3 ,4, 5 ]
for idx, arr in enumerate(arr):
    print('#%d: %d' % (idx + 1, arr))

#1: 1
#2: 2
#3: 3
#4: 4
#5: 5


برای یم لیست یک عضوی، حلقه کار نمیکند

In [105]:
arr= [1, 2, 3 ,4, 5 ]

In [107]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [108]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


In [109]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


In [110]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])  

cute


In [111]:
type(d)

dict

In [112]:
print('cat' in d) 

True


In [117]:
d={1:2, 3:4 , -1:5}

In [118]:
d

{-1: 5, 1: 2, 3: 4}

In [120]:
d[-1]

5

In [121]:
d['fish'] = 'wet' 

In [122]:
print(d.get('monkey', 'N/A'))

N/A


In [125]:
print(d.get('Ghoozfish', 'NADaaram')) 

NADaaram


In [126]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [127]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}

In [128]:
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


# Containers

# Sets


In [1]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals) 

True
False


In [2]:
animals.add('fish') 

In [3]:
type(animals)

set

In [4]:
print(len(animals))

3


In [20]:
animals = {'cat', 'dog', 'fish'}
num2= {2,4,3}
lis={[1,2],[4,5]}
animals2={{"a","d"},animals}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

TypeError: unhashable type: 'list'

In [6]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: fish


In [7]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: fish


In [9]:
animals[3]

TypeError: 'set' object does not support indexing

یعنی دیگه در مجموعه ها شما ایندکس نداری

In [11]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
nums2 = [int(sqrt(x)) for x in range(30)]
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"
print(nums2) 

{0, 1, 2, 3, 4, 5}
[0, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5]


این بالا تفاوت لیست و ست

# Conainers

## Tuples

In [30]:
t = (5, 6)        # Create a tuple
# A mozakhraf example
d = {(x, x + 1): x  for x in range(10)}  # Create a dictionary with tuple keys

print(d)
print(d[(0,1)])
print(type(t)) 

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
0
<class 'tuple'>


tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [31]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [33]:
sign([-1 , 1])

TypeError: '>' not supported between instances of 'list' and 'int'

In [34]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


optional keyword arguments

In [41]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

In [47]:
G=Greeter(1)
G.greet()


Hello, 1


In [49]:
G1=Greeter('Amin')
G1.greet(True)


HELLO, AMIN!


Jigareto

# Numpy
متلبه ولی پایتونه
## Arrays

In [50]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [51]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) 

(2, 3)
1 2 4


In [52]:
e = np.random.random((2,2))

In [53]:
e

array([[0.73210655, 0.7936107 ],
       [0.5550775 , 0.06846945]])

In [60]:
e = np.random.gamma((30,1,10,20,43))

In [61]:
e

array([34.71567133,  2.28780714,  9.44743364, 21.80115362, 42.38740135])

In [70]:
? np.random.random

In [67]:
e

array([[0.2279079 , 0.75408262],
       [0.61557253, 0.13646544],
       [0.91986573, 0.21122314],
       [0.04114989, 0.02074723],
       [0.07378153, 0.17240119],
       [0.96997716, 0.60473343],
       [0.84204157, 0.96335258],
       [0.65330509, 0.76594675],
       [0.08093705, 0.0292532 ],
       [0.12158595, 0.78451289]])

# Array indexing


In [72]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]

In [73]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
b

array([[2, 3],
       [6, 7]])

In [79]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [87]:
print(a)
print('\n')
i1=[0, 1, 2]

print(a[i1, [1 , 1, 0]])


[[1 2]
 [3 4]
 [5 6]]


[2 4 5]


#### Integer array indexing
#### Boolean array indexing

In [93]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print( bool_idx )
a[bool_idx]

[[False False]
 [ True  True]
 [ True  True]]


array([3, 4, 5, 6])

# Datatypes

In [94]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)   

int32
float64
int64


In [95]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [98]:

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [99]:
#BroadCasting

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

In [100]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [2]:
from scipy.misc import imread, imsave, imresize

ImportError: cannot import name 'imread'

In [3]:
import scipy as sp

In [ ]:
sp.import